name: Julia Package Registry
on:
  push:
    tags: ['*']
  workflow_dispatch:
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: MyExampleOrg/ExampleRegistry.jlworkflows/Registry.yml@master
        with:
         registrator_token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
         repository: ${{ github.repository }}
