name: Julia Package Registry
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pkg-registry:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Configure Git
        run: |
          # sudo apt-get update -qq && sudo apt-get install -y -qq git
          # git config --global user.email "artememelin@bootcamp-bhft.com"
          # git config --global user.name "artememelin"
          # echo -n "x-access-token:${{ secrets.TEST_TOKEN }}" > ~/.netrc && chmod 600 ~/.netrc
          gh auth login --with-token <<< ${{ secrets.TEST_TOKEN }}
          gh config set --global user.email "artememelin@bootcamp-bhft.com"
          gh config set --global user.name "artememelin"

      - name: Julia Package Registry Job
        env:
          JULIA_REGISTRY: "https://github.com/MyExampleOrg/ExampleRegistry.jl"
          REPOSITORY_PATH: "${{ github.repository }}"
          REPOSITORY_URL: "${{ github.repositoryUrl }}"
        run: |
          julia -e '
          using Pkg
          Pkg.update()
          
          Pkg.Registry.add(RegistrySpec(url = ENV["JULIA_REGISTRY"]))
          Pkg.develop(url = "https://github.com/" * ENV["REPOSITORY_PATH"] * ".git")
          
          Pkg.add("LocalRegistry")
          using LocalRegistry

          name = split(split("$(ENV["REPOSITORY_PATH"])", "/")[2], ".")[1]

          @info ENV["JULIA_REGISTRY"]
          LocalRegistry.register(
            name,
            registry = ENV["JULIA_REGISTRY"],
            commit = true, push = true,
            ignore_reregistration = true,
          )
          '
