name: Julia Package Registry
on:
  push:
    tags: ['*']
  workflow_dispatch:
env:
  registry_path: ${{ vars.EXAMPLEREGISTRY }}
jobs:
  registry:
    uses: ${{ env.registry_path }}
    secrets: inherit
