name: Julia Package Registry
on:
  push:
    tags: ['*']
  workflow_dispatch:
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: MyExampleOrg/ExampleRegistry.jl@master
        with:
         registrator_token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
         repository: ${{ github.repository }}
