name: Julia Package Registry
on:
  workflow_dispatch:
jobs:
  pkg-registry:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Configure Git
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq git
          git config --global user.email "artememelin@bootcamp-bhft.com"
          git config --global user.name "artememelin"
          echo -n "x-access-token:${{ secrets.TEST_TOKEN }}" > ~/.netrc && chmod 600 ~/.netrc

      - name: Julia Package Registry Job
        env:
          JULIA_REGISTRY: "https://github.com/MyExampleOrg/ExampleRegistry.jl"
          CI_PROJECT_NAME: ${{ github.action_repository}}
        run: |
          julia -e '
          name = first(split("$(ENV["CI_PROJECT_NAME"])", "."))
          println(name)
          println(1)
          '
