name: Julia Package Registry
on:
  push:
    tags: ['*']
  workflow_dispatch:
jobs:
  registry:
    uses: MyExampleOrg/ExampleRegistry.jl/.github/workflows/Registry.yml@master
    with:
     registrator_token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
     repository: ${{ github.repository }}
