name: Julia Package Registry
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pkg-registry:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Configure Git
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq git
          git config --global user.email "artememelin@bootcamp-bhft.com"
          git config --global user.name "artememelin"
          echo -n "x-access-token:${{ secrets.TEST_TOKEN }}" > ~/.netrc && chmod 600 ~/.netrc

      - name: Julia Package Registry Job
        env:
          JULIA_REGISTRY: "https://github.com/MyExampleOrg/ExampleRegistry.jl"
          REPOSITORY_PATH: "${{ github.repository }}"
        run: |
          julia -e '
          name = second(split("$(ENV["REPOSITORY_PATH"])", "/"))
          println(name)
          println(1)
          '
